name: build

on: workflow_dispatch

jobs: 
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: install requirements
        run: |
          sudo apt update 
          sudo apt install --yes make gcc libncurses-dev cpp gpp g++ unzip gawk
      - name: checkout site
        uses: actions/checkout@v3
        with:
          path: freifunk/site

      - name: clone gluon-changes
        uses: actions/checkout@v3
        with:
          repository: FreifunkHalle/gluon-package
          path: freifunk/gluon-package

      - name: clone gluon-package
        uses: actions/checkout@v3
        with:
          repository: FreifunkHalle/gluon-changes
          path: freifunk/gluon-changes

      - name: create symlinks
        run: |
          ln -s $(pwd)/freifunk/site ./freifunk/gluon-changes/site
          ln -s $(pwd)/freifunk/gluon-package/ffhal-ssh-keys ./freifunk/gluon-changes/package/
      
      - name: update repo
        run: |
          cd ./freifunk/gluon-changes
          make update
      
      - name: building firmware
        run: |
          cd ./freifunk/gluon-changes
          make GLUON_TARGET=ath79-generic
          make GLUON_TARGET=ath79-nand
          make GLUON_TARGET=ath79-mikrotik
          make GLUON_TARGET=brcm2708-bcm2708
          make GLUON_TARGET=brcm2708-bcm2709
          make GLUON_TARGET=ipq40xx-generic
          make GLUON_TARGET=ipq40xx-mikrotik
          make GLUON_TARGET=lantiq-xrx200
          make GLUON_TARGET=lantiq-xway
          make GLUON_TARGET=mediatek-filogic
          make GLUON_TARGET=mediatek-mt7622
          make GLUON_TARGET=mpc85xx-p1010
          make GLUON_TARGET=ramips-mt7620
          make GLUON_TARGET=ramips-mt7621
          make GLUON_TARGET=ramips-mt76x8
          make GLUON_TARGET=x86-generic

      - name: Write private key file from base64-encoded secret
        run: echo -e "${{ secrets.PRIVATE_KEY_BASE64 }}" | base64 --decode > /tmp/ssh-private-key.pem
      
      - name: Copy files to freifunk server
        run: scp -i /tmp/ssh-private-key.pem -R output/* github@www.freifunk-halle.org:/srv/github

